

CREATE TABLE IF NOT EXISTS mpa_rates
(
    mpa_id          int generated by default as identity primary key,
    name        varchar(50) NOT NULL,
    description varchar(200) NOT NULL
    );


CREATE TABLE IF NOT EXISTS films
(
    film_id         int generated by default as identity primary key,
    name            varchar(255) NOT NULL,
    description     varchar(200) NOT NULL,
    releaseDate     date NOT NULL       ,
    duration        int  NOT NULL       ,
    mpa_id          int         REFERENCES mpa_rates (mpa_id)
    );

CREATE TABLE IF NOT EXISTS users
(
    user_id         int generated by default as identity primary key,
    login           varchar(100) NOT NULL,
    name            varchar(100)NOT NULL UNIQUE,
    email           varchar(200)NOT NULL UNIQUE,
    birthday        date NOT NULL
    );

CREATE TABLE IF NOT EXISTS likes
(
    user_id int REFERENCES users (user_id),
    film_id int REFERENCES films (film_id),
    id int generated by default as identity primary key
    );

CREATE TABLE IF NOT EXISTS friends
(
    user_id   int NOT NULL REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    friend_id int NOT NULL REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS genres
(
    genre_id   int generated by default as identity primary key,
    name varchar(200) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  int REFERENCES films (film_id) ON DELETE CASCADE ON UPDATE CASCADE,
    genre_id int REFERENCES genres (genre_id) ON DELETE CASCADE ON UPDATE CASCADE,
    id int generated by default as identity primary key
    );



